In [ ]:
Практическое задание 1
Создайте два массива: первый - двумерный массив (матрица) размером 6x4, заполненный
числами от 10 до 33; второй - одномерный массив длины 4 с числами от 15 до 18. Выполните
поэлементное деление матрицы на одномерный массив, используя правила Broadcasting, и
вычислите след результирующей матрицы.

In [11]:
import numpy as np

matrix = np.arange(10, 34).reshape(6, 4)
array_1d = np.arange(15, 19)

print("Двумерный массив (матрица):")
print(matrix)
print("\nОдномерный массив:")
print(array_1d)
result_matrix = matrix / array_1d

print("\nРезультирующая матрица после деления:")
print(np.trace(result_matrix))

Двумерный массив (матрица):
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]

Одномерный массив:
[15 16 17 18]

Результирующая матрица после деления:
4.169526143790849


In [ ]:
Практическое задание 2
Создайте двумерный массив размером 3x8, заполненный числами от 1 до 24. Выполните
суммирование по первой оси (axis=0), посчитайте среднее значение по второй оси. Выведите
полученный результат.

In [14]:
matrix = np.arange(1, 25).reshape(3,8)
print("Двумерный массив (матрица):")
print(matrix)
sum_result = np.sum(matrix, axis=0)
mean_result = np.mean(matrix, axis=1)
print("\nСуммирование по первой оси (axis=0):")
print(sum_result)
print(mean_result)

Двумерный массив (матрица):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]

Суммирование по первой оси (axis=0):
[27 30 33 36 39 42 45 48]
[ 4.5 12.5 20.5]


In [1]:
import numpy as np
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# print(cube * cube)
print(cube + np.array([[10, 20], [30, 40]]))
# print(cube + np.array([[10, 20]]))
# print(cube + np.array([10, 20]))
# print(cube + np.array([[10], [20]]))

[[[11 22]
  [33 44]]

 [[15 26]
  [37 48]]]


In [19]:
import numpy as np
array = np.linspace(-2 * np.pi, 2 * np.pi, 20)
print("Массив:", array)
squared_cosines = np.cos(array) ** 2
print("Квадраты косинусов:", np.cos(array) ** 2)
print("Все элементы меньше или равны 1:", np.all(squared_cosines <= 1))

Массив: [-6.28318531 -5.62179738 -4.96040945 -4.29902153 -3.6376336  -2.97624567
 -2.31485774 -1.65346982 -0.99208189 -0.33069396  0.33069396  0.99208189
  1.65346982  2.31485774  2.97624567  3.6376336   4.29902153  4.96040945
  5.62179738  6.28318531]
Квадраты косинусов: [1.         0.62274274 0.06026312 0.16135921 0.77347408 0.97290862
 0.45871033 0.00681935 0.29915229 0.89457025 0.89457025 0.29915229
 0.00681935 0.45871033 0.97290862 0.77347408 0.16135921 0.06026312
 0.62274274 1.        ]
Все элементы меньше или равны 1: True


In [27]:
matrix = [[int(input(f"Введите значение для элемента [{i+1}, {j+1}]: ")) for i in range(2)]for j in range(3)]
matrix = np.array(matrix)
print(matrix)
matrix = np.array(matrix).reshape(3,2)
print(matrix)

Введите значение для элемента [1, 1]:  1
Введите значение для элемента [2, 1]:  2
Введите значение для элемента [1, 2]:  3
Введите значение для элемента [2, 2]:  4
Введите значение для элемента [1, 3]:  5
Введите значение для элемента [2, 3]:  6


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
Матрица goods описывает количество муки, яиц и сахара в трех видах десертов некоторой кондитерской. 
Известно, что затраты на выпечку первого десерта составляют 2 евро, второго – 4 евро, третьего – 3 евро. 
Найдите, сколько должны стоить мука, яйца и сахар для такой себестоимости десертов.
# Расход продуктов
goods = np.array(
[[0.5, 6, 0.1],
[1, 10, 0.5],
[0.3, 10, 0.6]]
)
Для решения задачи составить систему уравнений, найти определитель этой системы. Если определитель не равен нулю, найти обратную матрицу и значения переменных.
2 = 0.5*x + 6*y + 0.1*z
4 = 1*x + 10*y + 0.5*z 
3 = 0.3*x + 10*y + 0.6*z
Где:

x - стоимость муки
y - стоимость яиц
z - стоимость сахара

In [30]:
import numpy as np

# Матрица коэффициентов (затраты муки, яиц, сахара)
A = np.array([[0.5, 6, 0.1],
              [1, 10, 0.5],
              [0.3, 10, 0.6]])


# Вектор себестоимости десертов
b = np.array([2, 4, 3])

# Вычисляем определитель матрицы A
det_A = np.linalg.det(A)
print(f"Определитель матрицы A: {det_A:.2f}")

# Если определитель не равен 0, решаем систему
if det_A != 0:
    A_inv = np.linalg.inv(A)  # Обратная матрица
    X = np.dot(A_inv, b)      # Решение системы (стоимость муки, яиц, сахара)
    print("Определитель матрицы A:", det_A)
    print("Стоимость муки, яиц и сахара:", X)
else:
    print("Матрица A вырожденная, решение невозможно.")


Определитель матрицы A: -1.50
Определитель матрицы A: -1.4999999999999998
Стоимость муки, яиц и сахара: [1.6  0.18 1.2 ]


In [33]:
import numpy as np

# Матрица расхода продуктов
goods = np.array(([[0.5, 6, 0.1],
                   [1, 10, 0.5],
                   [0.3, 10, 0.6]])

# Затраты на выпечку десертов
costs = np.array([2, 4, 3])

# Вычисляем определитель матрицы goods
det_goods = np.linalg.det(goods)
print(f"Определитель матрицы goods: {det_goods:.2f}")

# Если определитель не равен нулю, решаем систему уравнений
if det_goods != 0:
    # Находим обратную матрицу
    goods_inv = np.linalg.inv(goods)
    
    # Решаем систему уравнений
    solution = goods_inv @ costs
    
    print("Решение системы уравнений:")
    print(f"Стоимость муки: {solution[0]:.2f} евро")
    print(f"Стоимость яиц: {solution[1]:.2f} евро") 
    print(f"Стоимость сахара: {solution[2]:.2f} евро")
else:
    print("Определитель матрицы равен нулю, система уравнений не имеет единственного решения.")


Определитель матрицы goods: -1.50
Решение системы уравнений:
Стоимость муки: 1.60 евро
Стоимость яиц: 0.18 евро
Стоимость сахара: 1.20 евро


In [ ]:
# Фирма закупает ноутбуки и стационарные компьютеры для оборудования офисов на двух этажах
# здания.
# ● На первом этаже планируется поставить 20 стационарных компьютеров и 20 ноутбуков.
# ● На втором этаже – 12 стационарных компьютеров и 35 ноутбуков.
# Компьютер стоит 850 евро, ноутбук – 1125 евро.
# 1. Запишите матрицу А, описывающую количество компьютеров и ноутбуков на каждом
# этаже.
# 2. Запишите вектор-столбец с ценами компьютеров и ноутбуков.
# 3. С помощью матричных операций вычислите стоимость оборудования на каждом этаже.

In [34]:
import numpy as np

# Матрица количества компьютеров и ноутбуков на этажах
A = np.array([[20, 20], 
              [12, 35]])

# Вектор цен компьютеров и ноутбуков
prices = np.array([850, 1125])

# Вычисляем стоимость оборудования на каждом этаже
costs = np.dot(A, prices)

print("Стоимость оборудования на каждом этаже:")
print(f"Первый этаж: {costs[0]:.2f} евро")
print(f"Второй этаж: {costs[1]:.2f} евро")


Стоимость оборудования на каждом этаже:
Первый этаж: 39500.00 евро
Второй этаж: 49575.00 евро


In [45]:
import numpy as np

A = np.array([[20, 20], [12, 35]])
b = np.array([40000, 50000])
z =  np.linalg.inv(A)
print(z@b)
x, y = np.linalg.inv(A)@b
# x, y = np.linalg.solve(A,b)

print(f"\nСтоимость одного ПК: {x:.2f} евро")
print(f"Стоимость одного ноутбука: {y:.2f} евро")


[ 869.56521739 1130.43478261]

Стоимость одного ПК: 869.57 евро
Стоимость одного ноутбука: 1130.43 евро


In [48]:
# Проверка предыдущего задания
# arr_x = np.array([[ 869.56521739], [1130.43478261]])
arr_x= np.array(z@b)
print(A @ arr_x )

[40000. 50000.]


In [ ]:
1. Создайте массив для анализа с помощью генерации чисел из разных
распределений.
Посчитайте и сравните средние значения и дисперсии полученных массивов
по осям (по столбцам и по строкам).
2. Напишите программу, которая:
● Запрашивает у пользователя количество точек данных N.
● Генерирует массив из N случайных точек (координаты x и y), используя
нормальное распределение.
● Выводит на экран первые 10 сгенерированных точек (если N было
больше 10.
● Вычисляет и выводит среднее значение и стандартное отклонение для
координат x и y.
Пример вывода:
Введите количество точек данных: 1000
Первые 10 точек: [(0.1, -0.2), (-1.3, 1.4), ...]
Среднее значение по x: 0.02
Стандартное отклонение по x: 1.0
Среднее значение по y: -0.03
Стандартное отклонение по y: 1.01

In [76]:
import numpy as np
import random as rd
# 1.массив для анализа с помощью генерации чисел из разных распределений
arr = np.random.randint(1, 2, size=(1000, 2000))  

mean_columns = np.mean(arr, axis=0)  # Средние значения по столбцам
mean_rows = np.mean(arr, axis=1)     # Средние значения по строкам
variance_columns = np.var(arr, axis=0)  # Дисперсия по столбцам
variance_rows = np.var(arr, axis=1)     # Дисперсия по строкам

print(arr)
normal_arr = np.random.normal(-0, 10, size=(3,2))
print(normal_arr)

# Вычисление средних значений и дисперсий
mean_uniform = np.mean(arr, axis=0), np.mean(arr, axis=1)
variance_uniform = np.var(arr, axis=0), np.var(arr, axis=1)
print (mean_uniform)
print (variance_uniform )

mean_normal = np.mean(normal_arr, axis=0), np.mean(normal_arr, axis=1)
variance_normal = np.var(normal_arr, axis=0), np.var(normal_arr, axis=1)
print (mean_normal)
print (variance_normal)


# 2. Программа для генерации точек данных

N = int(input("Введите количество точек данных: "))

# Генерация массива из N случайных точек
points = np.random.normal(loc=0, scale=1, size=(N, 2))  # Координаты x и y

# Вывод первых 10 точек
if N > 10:
    print("Первые 10 точек:", points[:10].tolist())
else:
    print("Все точки:", points.tolist())

# Вычисление среднего значения и стандартного отклонения
mean_x = np.mean(points[:, 0])
std_x = np.std(points[:, 0])

mean_y = np.mean(points[:, 1])
std_y = np.std(points[:, 1])

print(f"Среднее значение по x: {mean_x:.2f}")
print(f"Стандартное отклонение по x: {std_x:.2f}")
print(f"Среднее значение по y: {mean_y:.2f}")
print(f"Стандартное отклонение по y: {std_y:.2f}")




[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[ 1.50780414  6.08446971]
 [ 4.75688287 10.18662183]
 [15.61316343 -4.77744249]]
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

KeyboardInterrupt: Interrupted by user

In [77]:
arr = np.random.randint(1, 2, size=(1000, 2000))  
print (arr)
mean_columns = np.mean(arr, axis=0)  # Средние значения по столбцам
mean_rows = np.mean(arr, axis=1)     # Средние значения по строкам
variance_columns = np.var(arr, axis=0)  # Дисперсия по столбцам
variance_rows = np.var(arr, axis=1)     # Дисперсия по строкам
print(f"Средние значения по столбцам: {mean_columns}")
print(f"Дисперсия по столбцам: {variance_columns}")
print(f"Средние значения по строкам: {mean_rows}")
print(f"Дисперсия по строкам: {variance_rows}")

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
Средние значения по столбцам: [1. 1. 1. ... 1. 1. 1.]
Дисперсия по столбцам: [0. 0. 0. ... 0. 0. 0.]
Средние значения по строкам: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1

In [72]:
N = 5000
list_2d = [[i + N*j for i in range(N)] for j in range(N)]
array_2d = np.array(list_2d)
array_2d 

array([[       0,        1,        2, ...,     4997,     4998,     4999],
       [    5000,     5001,     5002, ...,     9997,     9998,     9999],
       [   10000,    10001,    10002, ...,    14997,    14998,    14999],
       ...,
       [24985000, 24985001, 24985002, ..., 24989997, 24989998, 24989999],
       [24990000, 24990001, 24990002, ..., 24994997, 24994998, 24994999],
       [24995000, 24995001, 24995002, ..., 24999997, 24999998, 24999999]],
      shape=(5000, 5000))

In [73]:
%%timeit
list_2d_mult = [[list_2d[i][j] * list_2d[i][j] for j in range(N)] for i in range(N)]

3.52 s ± 133 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
%%timeit
array_2d_mult = array_2d * array_2d

77.7 ms ± 2.53 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [75]:
%%timeit
arr = []
for i in range(N):
    subarr = []
    for j in range(N):
        subarr.append(list_2d[i][j] * list_2d[i][j])
    arr.append(subarr)

3.96 s ± 60.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
