In [ ]:
1. Напишите программу, которая:
● Запрашивает у пользователя ввод одномерного массива, элементы которого
вводятся в виде чисел, разделенных пробелами.
● Преобразует введенную строку в массив NumPy.
● Запрашивает у пользователя индекс элемента, который необходимо извлечь из
массива.
● Выводит значение элемента по запрошенному индексу.
● Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`,
чтобы извлечь срез массива.
● Выводит срез массива

In [1]:
import numpy as np

user_input = input("Введите массив (числа, разделенные пробелами): ").split()
array = np.array(user_input, dtype=int)

index = int(input("Введите индекс элемента: "))

print(f"Элемент с индексом {index}: {array[index]}")

range_input = input("Введите диапазон индексов (два числа, разделенные пробелами): ").split()
start, end = map(int, range_input)

slice_array = array[start:end]
print(f"Срез массива: {slice_array}")

Введите массив (числа, разделенные пробелами):  1 2 3 4 5
Введите индекс элемента:  2


Элемент с индексом 2: 3


Введите диапазон индексов (два числа, разделенные пробелами):  1 4 


Срез массива: [2 3 4]


In [ ]:
2. Напишите программу, которая:
● Запрашивает у пользователя размеры матрицы MxN.
● Генерирует две матрицы указанных размеров, заполненные случайными числами от 0
до 9.
● Выводит обе сгенерированные матрицы на экран.
● Выполняет и выводит результат одной из следующих операций (на выбор
пользователя): сложение матриц, умножение матриц, транспонирование одной из
матриц.
● Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам
матричного умножения.

In [13]:
import numpy as np
import random as rd
m = int(input("Введите количество строк (M): "))
n = int(input("Введите количество столбцов (N): "))

matrix_a = np.random.randint(0, 10, size=(m, n))
matrix_b = np.random.randint(0, 10, size=(m, n))

print("\nМатрица A:")
print(matrix_a)
print("\nМатрица B:")
print(matrix_b)

operation = input("\nВыберите операцию (сложение (+), умножение (*), транспонирование A(ta), транспонирование B(tb): ").lower()

if operation == "+":
    result = matrix_a + matrix_b
    print("\nРезультат сложения матриц:")
    print(result)
elif operation == "*":
    if n == m:
        result = matrix_a * matrix_b 
        print("\nРезультат умножения матриц:")
        print(result)
    else:
        print("\nОшибка: размеры матриц не соответствуют правилам матричного умножения.")

elif operation == "ta":
    result = matrix_a.T
    print("\nТранспонированная матрица A:")
    print(result)
elif operation == "tb":
    result = matrix_b.T
    print("\nТранспонированная матрица B:")
    print(result)
else:
    print("\nОшибка: неверная операция.")


Введите количество строк (M):  3
Введите количество столбцов (N):  3



Матрица A:
[[9 8 5]
 [6 4 7]
 [7 0 1]]

Матрица B:
[[3 3 0]
 [6 3 6]
 [8 0 2]]



Выберите операцию (сложение (+), умножение (*), транспонирование A(ta), транспонирование B(tb):  *



Результат умножения матриц:
[[27 24  0]
 [36 12 42]
 [56  0  2]]
