In [1]:
# 1. Сравнение производительности операций над массивами:
# Напишите программу, которая:
# - Генерирует два больших одномерных массива с 1 миллионом элементов каждый, заполненных случайными числами.
# - Сначала выполняет поэлементное сложение этих массивов, используя циклы Python.
# - Затем выполняет ту же операцию, используя возможности NumPy.
# - Измеряет и выводит время выполнения каждого подхода.

In [2]:
import numpy as np
import time
import random

array1 = [random.randint(0, 100) for i in range(1000000)]
array2 = [random.randint(0, 100) for i in range(1000000)]

# Python
start_time = time.time()
result_python = [array1[i] + array2[i] for i in range(1000000)]
python_time = time.time() - start_time

np_array1 = np.array(array1)
np_array2 = np.array(array2)

# NumPy
start_time = time.time()
result_numpy = np_array1 + np_array2
numpy_time = time.time() - start_time

print(f"Время выполнения сложения с использованием цикла Python: {python_time:.5f} секунды.")
print(f"Время выполнения сложения с использованием NumPy: {numpy_time:.5f} секунды.")

Время выполнения сложения с использованием цикла Python: 0.11710 секунды.
Время выполнения сложения с использованием NumPy: 0.00300 секунды.


In [ ]:
# 2. Анализ расположения данных в памяти:
# Создать большой двумерный массив и исследовать, как изменение порядка (C-style и Fortran-style) влияет на производительность операций сложения и умножения.

In [4]:
import numpy as np
import time
n = 10000
rand_list = np.random.rand(n * n)
c_array = rand_list.reshape(n, n)
f_array = rand_list.reshape(n, n, order='F')
print("C-style array:")
print(c_array)
print("\nFortran-style array:")
print(f_array)

C-style array:
[[0.21341603 0.90537502 0.70586423 ... 0.73891679 0.57243447 0.57314938]
 [0.87222758 0.92770146 0.93791558 ... 0.39910295 0.26337649 0.75203973]
 [0.39520065 0.6426213  0.29467523 ... 0.0861484  0.71970661 0.49296207]
 ...
 [0.76380399 0.83627547 0.30582895 ... 0.89404588 0.97984545 0.69010114]
 [0.93523059 0.49003165 0.68126953 ... 0.86181824 0.12705569 0.6884622 ]
 [0.98908781 0.4985884  0.53744445 ... 0.40776905 0.0931404  0.24513826]]

Fortran-style array:
[[0.21341603 0.87222758 0.39520065 ... 0.76380399 0.93523059 0.98908781]
 [0.90537502 0.92770146 0.6426213  ... 0.83627547 0.49003165 0.4985884 ]
 [0.70586423 0.93791558 0.29467523 ... 0.30582895 0.68126953 0.53744445]
 ...
 [0.73891679 0.39910295 0.0861484  ... 0.89404588 0.86181824 0.40776905]
 [0.57243447 0.26337649 0.71970661 ... 0.97984545 0.12705569 0.0931404 ]
 [0.57314938 0.75203973 0.49296207 ... 0.69010114 0.6884622  0.24513826]]


In [36]:
%%timeit
c_array + c_array

317 ms ± 17.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
%%timeit 
f_array + f_array

324 ms ± 22.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [38]:
%%timeit 
c_array * c_array

311 ms ± 9.75 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [40]:
%%timeit 
f_array * f_array

311 ms ± 4.98 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# 3. Обратная матрица и определитель:
# Напишите программу, которая:
# - Запрашивает у пользователя размер квадратной матрицы N.
# - Генерирует квадратную матрицу размером N x N, заполненную случайными числами от -10 до 10.
# - Выводит сгенерированную матрицу на экран.
# - Вычисляет и выводит определитель матрицы.
# - Если определитель не равен нулю, программа должна вычислить и вывести обратную матрицу. В противном случае, программа должна сообщить, что обратной матрицы не существует.

In [34]:
n = int(input("Введите размер матрицы N: "))

matrix = np.random.randint(-10, 11, size=(n, n))

print("\nСгенерированная матрица:")
print(matrix)

det = np.linalg.det(matrix)
print("\nОпределитель:", round(det, 2))

if det != 0:
    inv_matrix = np.linalg.inv(matrix)
    print("\nОбратная матрица:")
    print(inv_matrix)
else:
    print("\nОбратной матрицы не существует.")

Введите размер матрицы N:  3



Сгенерированная матрица:
[[ 9 -4  1]
 [ 6  1  2]
 [ 0  8  7]]

Определитель: 135.0

Обратная матрица:
[[-0.06666667  0.26666667 -0.06666667]
 [-0.31111111  0.46666667 -0.08888889]
 [ 0.35555556 -0.53333333  0.24444444]]
