In [3]:
import numpy as np
a = np.arange(16).reshape(4,4)
matrix = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

third_row = matrix[2]
result_1 = matrix * third_row
print(result_1)

second_column = matrix[:, 1]
result_2 = matrix - second_column.reshape(4, 1)
print(result_2)

[[  9  20  33  48]
 [ 45  60  77  96]
 [ 81 100 121 144]
 [117 140 165 192]]
[[-1  0  1  2]
 [-1  0  1  2]
 [-1  0  1  2]
 [-1  0  1  2]]


In [ ]:
# 1. Напишите программу, которая:
# a. Запрашивает у пользователя ввод двух списков – в первом 5 элементов, во втором 4.
# Списки вводятся в виде чисел, разделенных пробелами.
# b. Объединяет введенные списки в один новый список из 9 элементов.
# c. Преобразует полученный список в массив NumPy.
# d. Вычисляет минимальное, среднее и максимальное значение для полученного массива.

In [19]:
list1 = input("list1: ").split()
list1 = [int(x) for x in list1]

list2 = input("list2: ").split()
list2 = [int(x) for x in list2]

array = np.array(list1 + list2)
min_value = np.min(array)
mean_value = np.mean(array)
max_value = np.max(array)

print("combined_list:", array)
print("min_value:", min_value)
print("mean_value:", mean_value)
print("max_value :", max_value)


list1:  1 2 3 4 5
list2:  1 2 3 4


combined_list: [1 2 3 4 5 1 2 3 4]
min_value: 1
mean_value: 2.7777777777777777
max_value : 5


In [ ]:
2. С помощью функции np.linspace создайте массив из 9 элементов со значениями между
средним и максимальным из предыдущей задачи. Найдите поэлементную сумму массивов из
первой и второй задачи.

In [20]:
linspace_array = np.linspace(mean_value, max_value, 9)
print("Массив из 9 элементов", linspace_array)
sum_array = array + linspace_array
print("Сумма массивов:", sum_array)

Массив из 9 элементов [2.77777778 3.05555556 3.33333333 3.61111111 3.88888889 4.16666667
 4.44444444 4.72222222 5.        ]
Сумма массивов: [3.77777778 5.05555556 6.33333333 7.61111111 8.88888889 5.16666667
 6.44444444 7.72222222 9.        ]


In [ ]:
3. Создайте массив из десяти элементов 1, 2, …, 10. С помощью функции cumprod вычислите
кумулятивные произведения элементов этого массива.

In [44]:
array_10 = np.arange(1, 11)
print(array_10)
cumulative_product = np.cumprod(array_10)
print("Кумулятивные произведения элементов массива:", cumulative_product)


[ 1  2  3  4  5  6  7  8  9 10]
Кумулятивные произведения элементов массива: [      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [ ]:
4. Напишите программу, которая:
    a. Запрашивает у пользователя ввод трех списков, каждый из трех элементов.
    Списки вводятся в виде чисел, разделенных пробелами.
    b. Создает список из полученных списков.
    c. Преобразует полученный двумерный список в двумерный массив NumPy
    (назовем его матрицей А).
    d. Вычисляет среднее значение для полученного массива.

In [23]:
lists = []
for i in range(3):
    lst = list(map(int, input(f"Введите список {i + 1}): ").split()))
    lists.append(lst)
matrix_A = np.array(lists)
print("Матрица A:")
print(matrix_A)
mean_A = np.mean(matrix_A)
print("Среднее значение матрицы A:", mean_A)

Введите список 1):  1 2 3
Введите список 2):  4 5 6 
Введите список 3):  7 8 9


Матрица A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Среднее значение матрицы A: 5.0


In [ ]:
    5. Продолжите предыдущую программу. Далее она:
    a. Создает матрицу такого же размера, но заполненную вычисленным средним
    значением (назовем ее матрицей B).
    b. Разделите матрицу A на матрицу B - это будет матрица С.
    c. Создайте новую матрицу, заполненную логическими значениями – True, если
    элемент матрицы С больше 1, False – если меньше 1.


In [22]:
matrix_B = np.full(matrix_A.shape, mean_A)
print("Матрица B:")
print(matrix_B)

matrix_C = matrix_A / matrix_B
print("Матрица C:")
print(matrix_C)

logic_matrix = matrix_C > 1
print("Логическая матрица (C > 1):")
print(logic_matrix)


Матрица B:
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Матрица C:
[[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]
Логическая матрица (C > 1):
[[False False False]
 [False False  True]
 [ True  True  True]]


In [ ]:
6. Продолжите предыдущую программу. Далее она:
    a. Объединяет матрицы A и B в две новые матрицы – одну размера 3х6, другую – 6х3.
    b. Запрашивает у пользователя два числа - x и y.
    c. Первую матрицу умножает на x, из второй вычитает y.

In [30]:
combi_m_1 = np.hstack((matrix_A, matrix_B))
combi_m_2 = np.vstack((matrix_A, matrix_B))

x = int(input("Введите x: "))
y = int(input("Введите y: "))
res1 = combi_m_1  * x
res2 = combi_m_2 - y

print("Результат умножения на x:")
print (res1)

print("Результат вычитания y:")
print (res2)


Введите x:  2 
Введите y:  3


Результат умножения на x:
[[ 2.  4.  6. 10. 10. 10.]
 [ 8. 10. 12. 10. 10. 10.]
 [14. 16. 18. 10. 10. 10.]]
Результат вычитания y:
[[-2. -1.  0.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


In [ ]:
# Вариант решения 2 предыдущей задачи 6
combi_m_1 = concatenate((matrix_A, matrix_B),axis = 0) # по оси Х
combi_m_2 = concatenate((matrix_A, matrix_B),axis = 1) # по оси Y

x = int(input("Введите x: "))
y = int(input("Введите y: "))
res1 = combi_m_1  * x
res2 = combi_m_2 - y

print("Результат умножения на x:")
print (res1)

print("Результат вычитания y:")
print (res2)

In [ ]:
7. Напишите программу, которая запрашивает у пользователя три числа и создает трехмерный
массив соответствующей размерности, заполненный случайными числами. Выведите массив
на экран.

In [36]:
x = int(input("Введите  X: "))
y = int(input("Введите  Y: "))
z = int(input("Введите  Z: "))

arr3 = np.random.randint(1, 11, size=(x, y, z))  
print(arr3)

Введите  X:  2
Введите  Y:  3
Введите  Z:  4


[[[ 5  9  7  4]
  [ 2  1  1  9]
  [ 9  8  2  4]]

 [[ 6  9 10  9]
  [ 2  5  3  9]
  [ 9  9  3  1]]]


In [38]:
import random as rd
arr3_2 = [[[rd.randint(1, 100) for k in range(z)] for j in range(y)] for i in range(x)]
arr3_2 = np.array(arr3_2)
print(arr3_2)

[[[21 65 44 82]
  [83 40 77 53]
  [83 34 52  4]]

 [[84  8 84 81]
  [ 8 86 42 74]
  [92 86 20 48]]]


In [46]:
x = int(input("Введите  X: "))
y = int(input("Введите  Y: "))
z = int(input("Введите  Z: "))
rd_list = [rd.uniform(0, 10) for i in range (x * y * z)]

arr = np.array(rd_list)
print(arr)
arr = arr.reshape(x,y,z)
arr

Введите  X:  2
Введите  Y:  3
Введите  Z:  1


[5.56885901 6.02971418 1.10893652 5.87642366 8.60541866 4.28083923]


array([[[5.56885901],
        [6.02971418],
        [1.10893652]],

       [[5.87642366],
        [8.60541866],
        [4.28083923]]])

In [40]:
x = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
s = x[1:3:1]
print(s)
# [2.2 3.3]
s[0] = 101
print(s)
# [101. 3.3]
print(x)


[2.2 3.3]
[101.    3.3]
[  1.1 101.    3.3   4.4   5.5]
