In [ ]:
1. Напишите программу, которая:
a. Запрашивает у пользователя ввод двух списков – в первом 5 элементов, во втором 4.
Списки вводятся в виде чисел, разделенных пробелами.
b. Объединяет введенные списки в один новый список из 9 элементов.
c. Преобразует полученный список в массив NumPy.
d. Трансформирует одномерный массив в матрицу размера 3х3. Обозначим эту матрицу
Х.
e. Выводит полученную матрицу.

In [2]:
import numpy as np

list1 = [int(x) for x in input("Введите 5 чисел : ").split()]
list2 = [int(x) for x in input("Введите 4 числа : ").split()]

combined_list = list1 + list2
arr = np.array(combined_list)

matrix_X = arr.reshape(3, 3)
print("Матрица X:")
print(matrix_X)

Введите 5 чисел :  1 2 3 4 5
Введите 4 числа :  6 7 8 9


Матрица X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
2. Продолжение предыдущей задачи. Далее она:
a. В каждой строке и в каждом столбце находит среднее, максимум, минимум, сумму,
произведение.
b. Для всей матрицы находит среднее, максимум, минимум, сумму, произведение и след.
c. Выводит транспонированную матрицу для матрицы Х.

In [3]:
print("\nПо строкам и столбцам:")
for axis in [0, 1]:
    print(f"{'Строки' if axis == 0 else 'Столбцы'}:")
    print(f"Mean: {np.mean(matrix_X, axis=axis)}")
    print(f"Max: {np.max(matrix_X, axis=axis)}")
    print(f"Min: {np.min(matrix_X, axis=axis)}")
    print(f"Sum: {np.sum(matrix_X, axis=axis)}")
    print(f"Prod: {np.prod(matrix_X, axis=axis)}")

print("\nДля всей матрицы:")
print(f"Mean: {np.mean(matrix_X)}")
print(f"Max: {np.max(matrix_X)}")
print(f"Min: {np.min(matrix_X)}")
print(f"Sum: {np.sum(matrix_X)}")
print(f"Prod: {np.prod(matrix_X)}")
print(f"Trace: {np.trace(matrix_X)}")

matrix_X_T = matrix_X.T
print("\nТранспонированная матрица:")
print(matrix_X_T)


По строкам и столбцам:
Строки:
Mean: [4. 5. 6.]
Max: [7 8 9]
Min: [1 2 3]
Sum: [12 15 18]
Prod: [ 28  80 162]
Столбцы:
Mean: [2. 5. 8.]
Max: [3 6 9]
Min: [1 4 7]
Sum: [ 6 15 24]
Prod: [  6 120 504]

Для всей матрицы:
Mean: 5.0
Max: 9
Min: 1
Sum: 45
Prod: 362880
Trace: 15

Транспонированная матрица:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# 3. Продолжение предыдущей задачи. Далее она:
# a. Генерирует массив из трех случайных элементов. Этот вектор-строку
# обозначим А.
# b. Трансформирует вектор-строку в вектор-столбец. Его обозначим B.
# c. Матрицу Х умножает на вектор-строку А.
# d. Матрицу Х умножает на вектор-столбец B.
# e. Выполняет матричное умножение матриц из предыдущих пунктов.

In [4]:
import random as rd

print("Матрица X:")
print(matrix_X)

# vector_A = np.array([rd.uniform(0, 10) for i in range (3)])
vector_A = np.random.randint(1, 11, size=3)
print("\nВектор-строка A:")
print(vector_A)

vector_B = vector_A[:, np.newaxis]
print("\nВектор-столбец B:")
print(vector_B)

result_c = matrix_X * vector_A
print("\nУмножение матрицы X на вектор-строку A:")
print(result_c)

result_d = matrix_X * vector_B
print("\nУмножение матрицы X на вектор-столбец B:")
print(result_d)

result_e = result_c @ result_d
print("\nМатричное умножение результатов из пунктов c и d:")
print(result_e)

Матрица X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Вектор-строка A:
[10  7  4]

Вектор-столбец B:
[[10]
 [ 7]
 [ 4]]

Умножение матрицы X на вектор-строку A:
[[10 14 12]
 [40 35 24]
 [70 56 36]]

Умножение матрицы X на вектор-столбец B:
[[10 20 30]
 [28 35 42]
 [28 32 36]]

Матричное умножение результатов из пунктов c и d:
[[ 828 1074 1320]
 [2052 2793 3534]
 [3276 4512 5748]]


In [ ]:
4. Продолжение предыдущей задачи. Далее она:
a. Запрашивает у пользователя число i от 0 до 2.
b. Выводит строку i из матрицы Х.
c. Выводит столбец i из матрицы Х.

In [5]:
i = int(input("Введите число i от 0 до 2: "))
print("Матрица X:")
print(matrix_X)
print(f"\nСтрока {i} из матрицы X:")
print(matrix_X[i,])

print(f"\nСтолбец {i} из матрицы X:")
print(matrix_X[:, i])

Введите число i от 0 до 2:  0


Матрица X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Строка 0 из матрицы X:
[1 2 3]

Столбец 0 из матрицы X:
[1 4 7]


In [ ]:
5. Создайте матрицу 5х5 из чисел от 1 до 25. Из этой матрицы извлеките две подматрицы: С
размера 2х3 из левого верхнего угла исходной матрицы, и В размера 3х2 из правого нижнего
угла исходной матрицы. Найдите матричное произведение С на B и B на С.
Вопросы для обсуждения:
● Можно ли выполнить поэлементное умножение матриц B и С?
● Подумайте, как нужно преобразовать одну из этих матриц, чтобы поэлементное умножение
стало возможно. Выполните эту операцию.

In [6]:
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
print("\nИсходная матрица 5x5:")
print(matrix_5x5)

submatrix_C = matrix_5x5[:2, :3] # строки от 0 до 1 (не включая 2) и столбцы от 0 до 3 до конца (столбцы 0,1,2)
submatrix_B = matrix_5x5[2:, 3:] # строки с 2: до конца (строки 3,4,5) и столбцы с 3 до конца (столбцы 4,5)

print("\nПодматрица C (2x3):")
print(submatrix_C) 
print("\nПодматрица B (3x2):")
print(submatrix_B)

print("\nПроизведение C на B:")
print(submatrix_C @ submatrix_B)

print("\nПроизведение B на C:")
print(submatrix_B @ submatrix_C)

submatrix_B_T = submatrix_B.T
print("\nПоэлементное произведение B(транспонированная) на C:")
print(submatrix_B_T * submatrix_C)


Исходная матрица 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Подматрица C (2x3):
[[1 2 3]
 [6 7 8]]

Подматрица B (3x2):
[[14 15]
 [19 20]
 [24 25]]

Произведение C на B:
[[124 130]
 [409 430]]

Произведение B на C:
[[104 133 162]
 [139 178 217]
 [174 223 272]]

Поэлементное произведение B(транспонированная) на C:
[[ 14  38  72]
 [ 90 140 200]]


In [ ]:
6. Запросите у пользователя ввод трех чисел – x, y, z. Создайте трехмерный массив размера
x*y*z и заполните его числами от 10 до 20 с подходящим шагом. Выведите его. Запросите у
пользователя координаты элемента этого тензора и его новое значение. Замените
выбранный элемент на новое значение.
Вычислите среднее, максимум, минимум, сумму, произведение по каждой оси.

In [12]:
import numpy as np

x = int(input("Введите размерность x: "))
y = int(input("Введите размерность y: "))
z = int(input("Введите размерность z: "))

array_3d = np.linspace(10, 20, num=x*y*z).reshape(x, y, z)
# array_3d = array_3d.astype(np.int8)

print("Трехмерный массив:")
print(array_3d)

coords = input("Введите координаты элемента (x, y, z) через запятую: ")
new_value = int(input("Введите новое значение: "))

x_crd, y_crd, z_crd = map(int, coords.split(','))

if 0 <= x_crd < x and 0 <= y_crd < y and 0 <= z_crd < z:
    array_3d[x_crd, y_crd, z_crd] = new_value
else:
    print("Ошибка: координаты выходят за пределы массива.")
    
print("Измененный массив:")
print(array_3d)
for axis_num in range(array_3d.ndim):
    print(f"\n--- По оси {axis_num} ---")
    print(f"Среднее:\n{np.mean(array_3d, axis=axis_num)}")
    print(f"Максимум:\n{np.max(array_3d, axis=axis_num)}")
    print(f"Минимум:\n{np.min(array_3d, axis=axis_num)}")
    print(f"Сумма:\n{np.sum(array_3d, axis=axis_num)}")
    print(f"Произведение:\n{np.prod(array_3d, axis=axis_num)}")


Введите размерность x:  2
Введите размерность y:  2
Введите размерность z:  3


Трехмерный массив:
[[[10 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]]]


Введите координаты элемента (x, y, z) через запятую:  0,0,1
Введите новое значение:  55


Измененный массив:
[[[10 55 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]]]

--- По оси 0 ---
Среднее:
[[12.5 35.5 14. ]
 [15.  16.  17. ]]
Максимум:
[[15 55 17]
 [18 19 20]]
Минимум:
[[10 16 11]
 [12 13 14]]
Сумма:
[[25 71 28]
 [30 32 34]]
Произведение:
[[150 880 187]
 [216 247 280]]

--- По оси 1 ---
Среднее:
[[11.  34.  12.5]
 [16.5 17.5 18.5]]
Максимум:
[[12 55 14]
 [18 19 20]]
Минимум:
[[10 13 11]
 [15 16 17]]
Сумма:
[[22 68 25]
 [33 35 37]]
Произведение:
[[120 715 154]
 [270 304 340]]

--- По оси 2 ---
Среднее:
[[25.33333333 13.        ]
 [16.         19.        ]]
Максимум:
[[55 14]
 [17 20]]
Минимум:
[[10 12]
 [15 18]]
Сумма:
[[76 39]
 [48 57]]
Произведение:
[[6050 2184]
 [4080 6840]]


In [13]:
# Создаем два массива
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

# Конкатенация по оси 0 (по вертикали)
result_vertical = np.concatenate((array1, array2), axis=0)

# Конкатенация по оси 1 (по горизонтали)
result_horizontal = np.concatenate((array1, array2.T), axis=1)

print("Результат вертикальной конкатенации:")
print(result_vertical)

print("\nРезультат горизонтальной конкатенации:")
print(result_horizontal)

Результат вертикальной конкатенации:
[[1 2]
 [3 4]
 [5 6]]

Результат горизонтальной конкатенации:
[[1 2 5]
 [3 4 6]]
