In [ ]:
1. Задайте массив grades из оценок студентов (оценки от 0 до 100, количество элементов – по
количеству студентов в вашей группе). Напишите программу, которая увеличит все оценки на
10%.

In [39]:
import numpy as np

num = int(input("Количество студентов: "))

grades = np.random.randint(0, 101, size=num)
print("Оценки:")

grades_10 = np.minimum(grades * 1.1, 100)
# grades[grades>100] = 100
print("\nОценки + 10%:")
print(grades_10)

Количество студентов:  30


Оценки:
[ 52.8  82.5  16.5  35.2  42.9   2.2 107.8  34.1 101.2  88.   68.2  31.9
  81.4  53.9  23.1 107.8   3.3  70.4  48.4  40.7 102.3  75.9 100.1  67.1
  34.1  18.7  14.3  57.2  62.7   2.2]

Оценки + 10%:
[ 52.8  82.5  16.5  35.2  42.9   2.2 100.   34.1 100.   88.   68.2  31.9
  81.4  53.9  23.1 100.    3.3  70.4  48.4  40.7 100.   75.9 100.   67.1
  34.1  18.7  14.3  57.2  62.7   2.2]


In [ ]:
2. Задайте массив prices из цен на товары (цены от 1 до 100 евро, количество – не менее 10).
Сгенерируйте массив из булевых значений: False – для цен меньше 40 евро, True – для всех
остальных. С его помощью сделайте скидку 5% для товаров с ценой не ниже 40.

In [41]:
num = 10  
prices = np.random.randint(1, 101, size=num).astype(float)

print("Цены:")
print(prices)

arr = prices >= 40
print(arr)
# prices_5 = np.where(arr,prices *  0.95, prices )
prices_5 = prices.copy()
prices_5[arr] *=  0.95

print("\nЦены - 5%:")
print(prices_5)


Цены:
[88. 96. 35. 49. 50. 84. 86. 20. 95. 33.]
[ True  True False  True  True  True  True False  True False]

Цены - 5%:
[83.6  91.2  35.   46.55 47.5  79.8  81.7  20.   90.25 33.  ]


In [ ]:
Пусть у вас есть данные о ежедневных изменениях стоимости акций компании в
течение недели. Найдите изменение цены за каждый день, а также дни с
минимальным и максимальным изменением.
(Подсказка: Не забудьте, что когда вы ищите изменение в ценах, то кол-во значений
уменьшается на 1, т.к. первое значение не с чем сравнивать.)

In [43]:
prices = np.random.randint(1000,1300,7) 

price_c = np.diff(prices)
print(prices)
print("изменение цены за каждый день:", price_c)

days_of_week = ["понедельник", "вторник", "среда", "четверг", "пятница", "суббота", "воскресенье"]

max = np.argmax(price_c)
min = np.argmin(price_c)

good_day = days_of_week[max + 1]  # +1, т.к. первое значение не с чем сравнивать
bad_day = days_of_week[min + 1]

print("Лучший день:", good_day)
print("Худший день:", bad_day)


[1238 1192 1262 1257 1165 1190 1097]
изменение цены за каждый день: [-46  70  -5 -92  25 -93]
Лучший день: среда
Худший день: воскресенье


In [ ]:
4. Пять спортсменов участвовали в соревновании, в котором нужно было бежать 2 часа, плыть
1 час и ехать на велосипеде 5 часов.
Первый спортсмен бежал со скоростью 15 км/ч, плыл со скоростью 4 км/ч и ехал на
велосипеде со скоростью 25 км/ч.
Соответствующие скорости второго спортсмена: 14 км/ч, 5 км/ч, 27 км/ч.
Третий спортсмен: 16 км/ч, 5 км/ч, 23 км/ч.
Четвертый: 13 км/ч, 5.5 км/ч, 26 км/ч.
Пятый: 12 км/ч, 4.5 км/ч, 30 км/ч.
Побеждает тот, кто преодолел большее расстояние. Напишите программу, которая
определяет победителя.
(Подсказка: Подумайте, что здесь можно записать матрицей, что вектором, какая матричная
операция определяет пройденное расстояние.)

In [15]:
t = np.array([2, 1, 5])  # Бег, плавание, велоспорт

# Скорости спортсменов (в км/ч)
s = np.array([
    [15, 4, 25],  # Первый спортсмен
    [14, 5, 27],  # Второй спортсмен
    [16, 5, 23],  # Третий спортсмен
    [13, 5.5, 26],  # Четвертый спортсмен
    [12, 4.5, 30]   # Пятый спортсмен
])

#  расстояние
dist = s @ t 
print("Расстояния, пройденные спортсменами:", dist)

# победитель
win_i = np.argmax(dist)
win_dist = dist[win_i]
print("Победитель: Спортсмен", win_i + 1, " преодолел:", win_dist, "км")


[159.  168.  152.  161.5 178.5]
Расстояния, пройденные спортсменами: [159.  168.  152.  161.5 178.5]
Победитель: Спортсмен 5  преодолел: 178.5 км


In [ ]:
5. Сделайте срез матрицы из предыдущей задачи, чтобы получить квадратную матрицу (т.е.
оставляем только трех спортсменов). Сгенерируйте случайный столбец трех чисел от 100 до
200. Будем считать, что это расстояния, пройденные каждым спортсменом. Найдите
определитель полученной матрицы и матрицу, обратную к ней. Умножьте обратную матрицу
на случайный столбец (с помощью матричного умножения). Поясните, что вы нашли с
помощью такой операции. 

In [17]:
s_3 = s[:3, :]

# Генерация случайного столбца из трех чисел от 100 до 200
rand_c = np.random.randint(100, 201, size=(3, 1))

# Находим определитель
det = np.linalg.det(s_3)

# Находим обратную матрицу
inv_m = np.linalg.inv(s_3)

# Умножаем обратную матрицу на случайный столбец
res = inv_m @ random_column

# Вывод результатов
print("Срез матрицы (первые три спортсмена):")
print(s_3)
print("\nСлучайный столбец:")
print(rand_c)
print("\nОпределитель матрицы:", det)
print("\nОбратная матрица:")
print(inv_m)
print("\nУмножение обратную матрицу на случайный столбец:")
print(res)

# Если определитель равен нулю, это значит, что матрица вырождена и не имеет обратной.
# Обратная матрица позволяет "обратить" действие матрицы, то есть, если исходная матрица преобразует вектор, то умножение на обратную матрицу вернет нас к исходному вектору.
# Результат умножения: Это значит, что если спортсмены с соответствующими скоростями  будут двигаться с этими скоростями,
# они смогут преодолеть расстояния, указанные в random_column.

Срез матрицы (первые три спортсмена):
[[15.  4. 25.]
 [14.  5. 27.]
 [16.  5. 23.]]

Случайный столбец:
[[137]
 [119]
 [127]]

Определитель матрицы: -110.00000000000004

Обратная матрица:
[[ 0.18181818 -0.3         0.15454545]
 [-1.          0.5         0.5       ]
 [ 0.09090909  0.1        -0.17272727]]

Результат умножения обратной матрицы на случайный столбец:
[[ 16.54545455]
 [-40.        ]
 [  3.27272727]]


In [ ]:
Транспонируйте матрицу из задачи 4. Поясните смысл каждой строки новой матрицы. На
вектор какого размера ее можно умножить (дайте ответ для вектора-столбца и вектора строки, для поэлементного умножения и для матричного умножения). Объясните
практический смысл каждой операции.

In [24]:
s = np.array([
    [15, 4, 25],  # Первый спортсмен
    [14, 5, 27],  # Второй спортсмен
    [16, 5, 23],  # Третий спортсмен
    [13, 5.5, 26],  # Четвертый спортсмен
    [12, 4.5, 30]   # Пятый спортсмен
])

# Транспонирование матрицы
t_s = s.T

# Вывод транспонированной матрицы
print("Транспонированная матрица:")
print(t_s)

print("1. Скорости всех спортсменов в беге.")
print("2. Скорости всех спортсменов в плавании.")
print("3. Скорости всех спортсменов в велоспорте.")

# Вектор-столбец (размер 5x1)
vector_c= np.array([[1], [2], [3], [4], [5]])

# Умножение транспонированной матрицы на вектор-столбец
res_c = t_s @ vector_c

print("\nумножения транспонированной матрицы на вектор-столбец:")
print(res_c)

# Вектор-строка (размер 1x3)
vector_r = np.array([[1, 2, 3]])

# Умножение вектора-строки на транспонированную матрицу
res_r = vector_r @ t_s

print("\nумножения вектор-строки на транспонированную матрицу:")
print(res_r)

# Поэлементное умножение с вектором-столбцом
arr_c = t_s * vector_c.T

print("\nумножения транспонированной матрицы на вектор-столбец:")
print(arr)

# Поэлементное умножение с вектором-строкой

# /elementwise_result_row = transposed_speeds * row_vector
elementwise_result_row = t_s * vector_r.T
print("\nумножения транспонированной матрицы на вектор-строку:")
print(elementwise_result_row)


Транспонированная матрица:
[[15.  14.  16.  13.  12. ]
 [ 4.   5.   5.   5.5  4.5]
 [25.  27.  23.  26.  30. ]]
1. Скорости всех спортсменов в беге.
2. Скорости всех спортсменов в плавании.
3. Скорости всех спортсменов в велоспорте.

умножения транспонированной матрицы на вектор-столбец:
[[203. ]
 [ 73.5]
 [402. ]]

умножения вектор-строки на транспонированную матрицу:
[[ 98. 105.  95. 102. 111.]]

умножения транспонированной матрицы на вектор-столбец:
[ True False  True False  True False  True  True  True  True]

умножения транспонированной матрицы на вектор-строку:
[[15. 14. 16. 13. 12.]
 [ 8. 10. 10. 11.  9.]
 [75. 81. 69. 78. 90.]]


In [ ]:
 Умножая транспонированную матрицу на вектор-столбец, мы получаем вектор, в котором каждая компонента 
представляет собой сумму произведений скоростей каждого спортсмена на соответствующее значение из вектора.

In [ ]:
Объяснение:

Первая строка матрицы содержит скорости бега для каждого спортсмена.
Вторая строка матрицы содержит скорости плавания для каждого спортсмена.
Третья строка матрицы содержит скорости езды на велосипеде для каждого спортсмена.
Теперь рассмотрим, с какими векторами можно выполнять различные операции с этой матрицей.

Умножение на вектор-столбец:

Вектор-столбец должен иметь размерность 5x1, чтобы соответствовать первому измерению транспонированной матрицы.
Результатом будет вектор-столбец размерности 3x1, содержащий суммарные расстояния, пройденные каждым спортсменом.
Практический смысл: Можно использовать этот вектор для определения победителя, как в предыдущей задаче.
Умножение на вектор-строку:

Вектор-строка должен иметь размерность 1x3, чтобы соответствовать второму измерению транспонированной матрицы.
Результатом будет вектор-строка размерности 1x5, содержащий суммарные скорости для каждого этапа соревнования.
Практический смысл: Можно использовать этот вектор для анализа и сравнения скоростей спортсменов на каждом этапе.
Поэлементное умножение:

Можно выполнять поэлементное умножение транспонированной матрицы на вектор-столбец или вектор-строку.
Результатом будет матрица того же размера, содержащая произведения соответствующих элементов.
Практический смысл: Можно использовать для расчета расстояний, пройденных каждым спортсменом на каждом этапе.
Матричное умножение:

Можно выполнять матричное умножение транспонированной матрицы на вектор-столбец или вектор-строку.
Результатом будет вектор-столбец или вектор-строка соответствующего размера.
Практический смысл: Можно использовать для расчета общих расстояний, пройденных каждым спортсменом, или для анализа средних скоростей на каждом этапе.

In [3]:
import numpy as np
a = np.array([1, 2, 3]) 
print(a)

# Shape: (3,)
b = a[np.newaxis, :]   
print(b)
# Shape: (1, 3)
# или
b = a[None, :]                  # Shape: (1, 3)
b

[1 2 3]
[[1 2 3]]


array([[1, 2, 3]])

In [4]:
a = np.array([1, 2, 3])         # Shape: (3,)
c = a[:, np.newaxis]   
print(c)
# Shape: (3, 1)
# или
c = a[:, None]  
print(c)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [5]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])  # 2D массив
print(a.shape)  # Вывод: (2, 3)
print(a.ndim)  # Вывод: 2 (количество измерений)


(2, 3)
2


In [6]:
import numpy as np
a = np.array([[0, 0, 0],
 [10, 10, 10],
 [20, 20, 20],
 [30, 30, 30]])
b = np.array([0, 1, 2])
result = a / (b + 1)
print(result)

[[ 0.          0.          0.        ]
 [10.          5.          3.33333333]
 [20.         10.          6.66666667]
 [30.         15.         10.        ]]


In [26]:
price = 50
is_discount = False

discounted_price = price * is_discount
print(discounted_price)  # Результат: 0


0
