In [2]:
import pandas as pd
import numpy as np

l = [1, 3, 5, np.nan, 6, 8]
d = pd.date_range('20160101', periods=6)
d
# DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
# '2016-01-05', '2016-01-06'],
# dtype='datetime64[ns]', freq='D')
s = pd.Series(l, index=d)
s

2016-01-01    1.0
2016-01-02    3.0
2016-01-03    5.0
2016-01-04    NaN
2016-01-05    6.0
2016-01-06    8.0
Freq: D, dtype: float64

In [3]:
s[s>3]

2016-01-03    5.0
2016-01-05    6.0
2016-01-06    8.0
dtype: float64

In [4]:
s = pd.Series(l)
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [6]:
s.values, type(s.values)
# (array([ 1., 3., 5., nan, 6., 8.]), numpy.ndarray)
s.to_dict()
# {0: 1.0, 1: 3.0, 2: 5.0, 3: nan, 4: 6.0, 5: 8.0}

{0: 1.0, 1: 3.0, 2: 5.0, 3: nan, 4: 6.0, 5: 8.0}

In [ ]:
s.index
# RangeIndex(start=0, stop=6, step=1)

In [7]:
# Что делает s.describe():
# count: количество ненулевых значений.
# mean: среднее значение.
# std: стандартное отклонение.
# min: минимальное значение.
# 25%: 25-й процентиль (первый квартиль).
# 50%: медиана (50-й процентиль).
# 75%: 75-й процентиль (третий квартиль).
# max: максимальное значение
s.describe()

count    5.000000
mean     4.600000
std      2.701851
min      1.000000
25%      3.000000
50%      5.000000
75%      6.000000
max      8.000000
dtype: float64

In [8]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s[2]

np.float64(5.0)

In [11]:
s[2] = 7 
s

0    1.0
1    3.0
2    7.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [12]:
s[2:5]


2    7.0
3    NaN
4    6.0
dtype: float64

In [13]:
s1 = s[1:]
s1

1    3.0
2    7.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [14]:
s2 = s[:-1]
s2

0    1.0
1    3.0
2    7.0
3    NaN
4    6.0
dtype: float64

In [15]:
s1 + s2

0     NaN
1     6.0
2    14.0
3     NaN
4    12.0
5     NaN
dtype: float64

In [16]:
np.exp(s1)
type(np.exp(s)), type(s)

(pandas.core.series.Series, pandas.core.series.Series)

In [17]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube[1, 0, 1])
print(cube[:, 1, 0])
print(cube[:, 1])

6
[3 7]
[[3 4]
 [7 8]]


In [18]:
s = pd.Series([1, 2, 3, 4, 5, 6])
t = s[2:]+s[:2]
print(t)
print(t.dropna())

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
dtype: float64
Series([], dtype: float64)


In [ ]:
Посчитайте кумулятивное среднее квадратов разностей соседних элементов набора s.
От них можно избавиться при помощи метода dropna.

In [22]:
import pandas as pd

# Пример набора данных
s = pd.Series([1, 2, 9, 6, 10])

# Вычисление разностей
differences = s.diff()
print(differences)
# Возведение в квадрат
squared_differences = differences ** 2
print(squared_differences)
# Кумулятивное среднее
cumulative_mean = squared_differences.cumsum() / (squared_differences.notna().cumsum())

# Удаление NaN значений
cumulative_mean_cleaned = cumulative_mean.dropna()

print(cumulative_mean_cleaned)


0    NaN
1    1.0
2    7.0
3   -3.0
4    4.0
dtype: float64
0     NaN
1     1.0
2    49.0
3     9.0
4    16.0
dtype: float64
1     1.000000
2    25.000000
3    19.666667
4    18.750000
dtype: float64


In [25]:
# Сгенерируйте массив точек в 3D, создайте по нему датафрейм и отсортируйте строки в порядке
# следования осей.
pd.DataFrame(np.random.normal(size=(10, 3)).astype(int), columns=['x', 'y', 'z']).sort_values(by=['x', 'y', 'z']) That's all. is this from now? Switch to Orkut. No, no, no. You know, I love

x  y  z
0 -1  0  1
9 -1  1  0
5  0  0 -1
1  0  0  0
3  0  0  0
4  0  0  0
7  0  0  0
8  0  0  0
6  0  0  2
2  1  0  0

In [28]:
d = {'one': pd.Series(range(6), index=list('abdefg')),
 'two': pd.Series(range(7), index=list('abcdefg')),
 'three': pd.Series(np.random.normal(size=7), index=list('abcdefg'))}
df = pd.DataFrame(d)
df

one  two     three
a  0.0    0  0.735327
b  1.0    1 -0.693545
c  NaN    2  1.498307
d  2.0    3  0.330720
e  3.0    4  1.093429
f  4.0    5  0.730899
g  5.0    6 -0.367907

In [37]:
data = {
    'one': [0.0, 1.0, np.nan, 2.0, 3.0, 4.0, 5.0, np.nan],
    'two': [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, np.nan],
    'three': [-0.359411, 1.166335, 2.130503, -1.510119, -0.012951, 0.152515, np.nan, 0.589751]
}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'k'])

print(df)

   one  two     three
a  0.0  0.0 -0.359411
b  1.0  1.0  1.166335
c  NaN  2.0  2.130503
d  2.0  3.0 -1.510119
e  3.0  4.0 -0.012951
f  4.0  5.0  0.152515
g  5.0  6.0       NaN
k  NaN  NaN  0.589751


In [38]:
print(df.one)  # К столбцу можно обращаться как к полю объекта, если имя столбца позволяет это сделать (= является строкой)
print(df['one'].index)  # Индекс полученного одномерного набора данных.
print(df['one'].name)  # Можно получить имя данного столбца
print(df['one']['d'])  # Получение элемента массива. Сначала надо указать столбец, потом строку
# df['c']['one'] # А наоборот нельзя! (Эта строка закомментирована, так как она не работает)

a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
k    NaN
Name: one, dtype: float64
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'k'], dtype='object')
one
2.0


In [41]:
# Примеры доступа к данным
print(df['b':'d'])  # Права граница включена!
print(df[1:3])      # Диапазон целых чисел не включает правую границу
# Эта команда будет выдавать ошибку, потому что обратиться по номеру к индексу нельзя.:
# print(df[1])        # Обращение по индексу ошибка!

# Срез нескольких столбцов
print(df[['one', 'three']])  # Выводит столбцы 'one' и 'three'

# Использование display для вывода
from IPython.display import display
display(df['one'])          # Выводит столбец 'one'
display(df[['one']])       # Выводит DataFrame с одним столбцом 'one'

   one  two     three
b  1.0  1.0  1.166335
c  NaN  2.0  2.130503
d  2.0  3.0 -1.510119
   one  two     three
b  1.0  1.0  1.166335
c  NaN  2.0  2.130503
   one     three
a  0.0 -0.359411
b  1.0  1.166335
c  NaN  2.130503
d  2.0 -1.510119
e  3.0 -0.012951
f  4.0  0.152515
g  5.0       NaN
k  NaN  0.589751


a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
k    NaN
Name: one, dtype: float64

one
a  0.0
b  1.0
c  NaN
d  2.0
e  3.0
f  4.0
g  5.0
k  NaN

In [46]:
# Получение строки с индексом 'b'
print("Строка с индексом 'b':")
print(df.loc['b'])

# Получение значения в ячейке с индексом строки 'b' и столбца 'one'
print("\ndf.loc['b', 'one'] Значение в ячейке с индексом строки 'b' и столбца 'one':")
print(df.loc['b', 'one'])

# Получение значения в ячейке с индексом строки 'b' и столбца 'one' (альтернативный способ)
print("\ndf['one']['b'] То же значение, но другим способом: ")
print(df['one']['b'])

# Получение значений в столбце 'one' для строк с индексами от 'a' до 'b' (включительно)
print("\ndf.loc['a':'b', 'one'] Значения в столбце 'one' для строк с индексами от 'a' до 'b':")
print(df.loc['a':'b', 'one'])

# Получение всех столбцов для строк с индексами от 'a' до 'b' (включительно)
print("\ndf.loc['a':'b', :] Все столбцы для строк с индексами от 'a' до 'b':")
print(df.loc['a':'b', :])

# Получение всех значений в столбце 'one'
print("\ndf.loc[:, 'one'] Все значения в столбце 'one':")
print(df.loc[:, 'one'])

# Получение строки с числовым индексом 2 (третья строка)
print("\ndf.iloc[2] Строка с числовым индексом 2:")
print(df.iloc[2])

# Получение строк с числовыми индексами от 1 до 2 (включительно)
print("\ndf.iloc[1:3] Строки с числовыми индексами от 1 до 2:")
print(df.iloc[1:3])

# Получение значений в столбцах с индексами от 0 до 1 (включительно) 
# для строк с индексами от 1 до 2 (включительно)
print("\ndf.iloc[1:3, 0:2] Значения в столбцах от 0 до 1 для строк от 1 до 2:")
print(df.iloc[1:3, 0:2])



Строка с индексом 'b':
one      1.000000
two      1.000000
three    1.166335
Name: b, dtype: float64

df.loc['b', 'one'] Значение в ячейке с индексом строки 'b' и столбца 'one':
1.0

df['one']['b'] То же значение, но другим способом: 
1.0

df.loc['a':'b', 'one'] Значения в столбце 'one' для строк с индексами от 'a' до 'b':
a    0.0
b    1.0
Name: one, dtype: float64

Все столбцы для строк с индексами от 'a' до 'b':
   one  two     three
a  0.0  0.0 -0.359411
b  1.0  1.0  1.166335

df.loc[:, 'one'] Все значения в столбце 'one':
a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
k    NaN
Name: one, dtype: float64

df.iloc[2] Строка с числовым индексом 2:
one           NaN
two      2.000000
three    2.130503
Name: c, dtype: float64

df.iloc[1:3] Строки с числовыми индексами от 1 до 2:
   one  two     three
b  1.0  1.0  1.166335
c  NaN  2.0  2.130503

df.iloc[1:3, 0:2] Значения в столбцах от 0 до 1 для строк от 1 до 2:
   one  two
b  1.0  1.0
c  NaN  2.0


In [47]:
df[df.three > 0]


one  two     three
b  1.0  1.0  1.166335
c  NaN  2.0  2.130503
f  4.0  5.0  0.152515
k  NaN  NaN  0.589751

In [50]:
print(df.notna())

     one    two  three
a   True   True   True
b   True   True   True
c  False   True   True
d   True   True   True
e   True   True   True
f   True   True   True
g   True   True  False
k  False  False   True


In [54]:
print(df.dropna())

   one  two     three
a  0.0  0.0 -0.359411
b  1.0  1.0  1.166335
d  2.0  3.0 -1.510119
e  3.0  4.0 -0.012951
f  4.0  5.0  0.152515


In [52]:
print(df)

   one  two     three
a  0.0  0.0 -0.359411
b  1.0  1.0  1.166335
c  NaN  2.0  2.130503
d  2.0  3.0 -1.510119
e  3.0  4.0 -0.012951
f  4.0  5.0  0.152515
g  5.0  6.0       NaN
k  NaN  NaN  0.589751


In [ ]:
Сгенерируйте случайную целочисленную матрицу 𝑛×𝑚 , где 𝑛=20,𝑚=10 . Создайте из нее датафрейм,
пронумеровав столбцы случайной перестановкой чисел из {1,…,𝑚} . Выберите столбцы с четными номерами и
строки, в которых четных элементов больше, чем нечетных.

In [75]:
import pandas as pd
import numpy as np
n, m = 20, 10
np.random.seed(42)
# Генерация случайной целочисленной матрицы 20x10
matrix = np.random.randint(1, 101, size=(n,m))
heads = np.arange(1,m+1)
print(matrix)
np.random.shuffle(heads)
print(heads)
# # Создание DataFrame с перенумерованными столбцами
df = pd.DataFrame(matrix, columns = heads )
print(df)
# Выбор столбцов с четными номерами
heads_mask = (heads % 2 == 0)
# Выбор строк с четными номерами
row_mask = np.sum(matrix % 2, axis=1) < m/2
print(heads_mask )      # True  True False  True  True  True False False False False
print(row_mask)       # False False False False False  True  True False]

print("Сгенерированная матрица:")
print(df.loc[row_mask,heads_mask])

[[ 52  93  15  72  61  21  83  87  75  75]
 [ 88 100  24   3  22  53   2  88  30  38]
 [  2  64  60  21  33  76  58  22  89  49]
 [ 91  59  42  92  60  80  15  62  62  47]
 [ 62  51  55  64   3  51   7  21  73  39]
 [ 18   4  89  60  14   9  90  53   2  84]
 [ 92  60  71  44   8  47  35  78  81  36]
 [ 50   4   2   6  54   4  54  93  63  18]
 [ 90  44  34  74  62 100  14  95  48  15]
 [ 72  78  87  62  40  85  80  82  53  24]
 [ 26  89  60  41  29  15  45  65  89  71]
 [  9  88   1   8  88  63  11  81   8  35]
 [ 35  33   5  41  28   7  73  72  12  34]
 [ 33  48  23  62  88  37  99  44  86  91]
 [ 35  65  99  47  78   3   1   5  90  14]
 [ 27   9  79  15  90  42  77  51  63  96]
 [ 52  96   4  94  23  15  43  29  36  13]
 [ 32  71  59  86  28  66  42  45  62  57]
 [  6  28  28  44  84  30  62  75  92  89]
 [ 62  97   1  27  62  77   3  70  72  27]]
[ 6  8  7 10  4  2  3  1  5  9]
    6    8   7   10  4    2   3   1   5   9 
0   52   93  15  72  61   21  83  87  75  75
1   88  100  24  