In [4]:
import numpy as np
# Вектор ежедневных расходов (в евро)
daily_expenses = np.array([10, 20, 15, 10, 30, 50, 50])
# Температура воздуха по месяцам (в градусах Цельсия)
temperature = np.array([1, 2, 6, 11, 16, 19, 21, 21, 16, 11, 6, 2])

In [6]:
# Перевод ежедневных расходов в доллары
print(daily_expenses * 1.1)
# [11. 22. 16.5 11. 33. 55. 55. ]
# Перевод температуры в Фаренгейты
print(1.8 * temperature + 32)
# [33.8 35.6 42.8 51.8 60.8 66.2 69.8 69.8 60.8 51.8 42.8 35.6]

[11.  22.  16.5 11.  33.  55.  55. ]
[33.8 35.6 42.8 51.8 60.8 66.2 69.8 69.8 60.8 51.8 42.8 35.6]


In [7]:
# Доходы мужа по месяцам (в евро)
income_m = np.array([2000, 3000, 3500, 3000, 3000, 2500, 3500, 2000, 2500, 3000, 3500, 4000])
# Доходы жены по месяцам (в евро)
income_f = np.array([1500, 2500, 6000, 1100, 1600, 1900, 2100, 4200, 6000, 1100, 6000, 2000])
# Курс евро к доллару по месяцам
eur2usd = np.array([1.0779, 1.0716, 1.071, 1.096, 1.0879, 1.0834, 1.1056, 1.0916, 1.0686, 1.0561,
1.0804, 1.0902])
# Семейный доход в евро
income = income_m + income_f
print(income)
# [3500 5500 9500 4100 4600 4400 5600 6200 8500 4100 9500 6000]
# Семейный доход в долларах
income_usd = income * eur2usd
print(income_usd)
# [ 3772.65 5893.8 10174.5 4493.6 5004.34 4766.96 6191.36 6767.92
# 9083.1 4330.01 10263.8 6541.2 ]

[3500 5500 9500 4100 4600 4400 5600 6200 8500 4100 9500 6000]
[ 3772.65  5893.8  10174.5   4493.6   5004.34  4766.96  6191.36  6767.92
  9083.1   4330.01 10263.8   6541.2 ]


In [ ]:
# Кондитерская производит несколько видов десертов.
# Для каждого необходимы мука, яйца и сахар, но в разном количестве.
# Необходимое количество описать матрицей, в которой каждая строка описывает одну партию какого-то десерта,
# при этом первый столбец показывает количество муки в килограммах, второй столбец – количество яиц в штуках,
# третий – количество сахара в килограммах.

In [8]:
# Расход продуктов
goods = np.array([[0.5, 6, 0.1],
 [1, 10, 0.5],
 [0.3, 10, 0.6],
 [0.5, 7, 0.3]])
print(goods)

[[ 0.5  6.   0.1]
 [ 1.  10.   0.5]
 [ 0.3 10.   0.6]
 [ 0.5  7.   0.3]]


In [22]:
# Пусть у нас также известна стоимость килограмма муки, одного яйца и килограмма сахара.
prices = np.array([0.75, 0.22, 0.88])
prices_col = prices.reshape(3,1)
expenses = goods @ prices_col
print(expenses)
total_costs = expenses.sum()
print(total_costs)

[[1.783]
 [3.39 ]
 [2.953]
 [2.179]]
10.305000000000001


In [29]:
# Фирма закупает ноутбуки и стационарные компьютеры для оборудования офисов на двух этажах
# здания.
# ● На первом этаже планируется поставить 20 стационарных компьютеров и 20 ноутбуков.
# ● На втором этаже – 12 стационарных компьютеров и 35 ноутбуков.
# Компьютер стоит 850 евро, ноутбук – 1125 евро.
# 1. Запишите матрицу А, описывающую количество компьютеров и ноутбуков на каждом
# этаже.
# 2. Запишите вектор-столбец с ценами компьютеров и ноутбуков.
# 3. С помощью матричных операций вычислите стоимость оборудования на каждом этаже.

A = np.array([[20, 20], 
              [12, 35]])

prices = np.array([[850], [1125]])
print(prices)

print(A @ prices)

[[ 850]
 [1125]]
[[39500]
 [49575]]


In [ ]:
C: C @ A = E -- определение C = A ** (-1)

A @ X = B -- задача найти X
=====
C @ A @ X = C @ B
E @ X = C @ B
X = C @ B

In [30]:
equipment = np.array([[20, 20], [12, 35]])

inverse = np.linalg.inv(equipment) # обратная матрица

# print(inverse) # A ** (-1)
print(inverse @ equipment)
print(equipment @ inverse) 
# A @ (A ** (-1)) = E то и  
# (A ** (-1)) @ A  = E

[[ 1.00000000e+00  1.38777878e-16]
 [-1.11022302e-16  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  1.00000000e+00]]


In [33]:
# Фирма закупает ноутбуки и стационарные компьютеры для оборудования офисов на двух этажах здания.
# ● На первом этаже планируется поставить 20 стационарных компьютеров и 20 ноутбуков.
# ● На втором этаже – 12 стационарных компьютеров и 35 ноутбуков.
# Стоимость оборудования первого этажа должна составить 40000 евро, а второго этажа – 50000.

equipment = np.array([[20, 20], [12, 35]])
expenses = np.array([[40000], [50000]])

inverse = np.linalg.inv(equipment)

x = inverse @ expenses # цены на компьютеры и ноутбуки
x

array([[ 869.56521739],
       [1130.43478261]])

In [32]:
# Выполните проверку, что полученный вектор цен удовлетворяет матричному уравнению –
# подставьте значения в уравнения или выполните умножение матрицы на этот столбец.

equipment @ x

array([[40000.],
       [50000.]])

In [37]:
equipment = np.array([[20, 20], [12, 35]])
# equipment = np.array([[20, 20], [30, 30]])
det = np.linalg.det(np.array([[20, 20], [12, 35]]))

print(det)

459.9999999999997


In [ ]:
Матрица goods, как в примере выше, описывает количество муки, яиц и сахара в трех видах десертов некоторой
кондитерской. Известно, что затраты на выпечку первого десерта составляют 2 евро, второго – 4 евро, третьего –
3 евро.
Найдите, сколько должны стоить мука, яйца и сахар для такой себестоимости десертов.

In [43]:
import numpy as np

# Матрица расхода продуктов
goods = np.array([[0.5, 6, 0.1],
                   [1, 10, 0.5],
                   [0.3, 10, 0.6]])

# Затраты на выпечку десертов
costs = np.array([2, 4, 3])

# Вычисляем определитель матрицы goods
det_goods = np.linalg.det(goods)
print(f"Определитель матрицы goods: {det_goods:.2f}")

# Если определитель не равен нулю, решаем систему уравнений
if det_goods != 0:
    # Находим обратную матрицу
    goods_inv = np.linalg.inv(goods)
    
    # Решаем систему уравнений
    solution = (goods_inv @ costs).reshape(3,1)
    print(solution)
    
    print("Решение системы уравнений:")
    print(f"Стоимость муки: {solution[0,0]:.2f} евро")
    print(f"Стоимость яиц: {solution[1,0]:.2f} евро") 
    print(f"Стоимость сахара: {solution[2,0]:.2f} евро")
else:
    print("Определитель матрицы равен нулю, система уравнений не имеет единственного решения.")


Определитель матрицы goods: -1.50
[[1.6 ]
 [0.18]
 [1.2 ]]
Решение системы уравнений:
Стоимость муки: 1.60 евро
Стоимость яиц: 0.18 евро
Стоимость сахара: 1.20 евро


In [44]:
import numpy as np

arr = np.random.randint(-10, 10, size=(3, 2))  

mean_columns = np.mean(arr, axis=0)  # Средние значения по столбцам
mean_rows = np.mean(arr, axis=1)     # Средние значения по строкам
variance_columns = np.var(arr, axis=0)  # Дисперсия по столбцам
variance_rows = np.var(arr, axis=1)     # Дисперсия по строкам
print(f"Средние значения по столбцам: {mean_columns}")
print(f"Дисперсия по столбцам: {variance_columns}")
print(f"Средние значения по строкам: {mean_rows}")
print(f"Дисперсия по строкам: {variance_rows}")

Средние значения по столбцам: [-3.         -0.66666667]
Дисперсия по столбцам: [16.66666667 10.88888889]
Средние значения по строкам: [-1.5 -2.5 -1.5]
Дисперсия по строкам: [12.25 30.25  2.25]


In [47]:
norm = np.random.normal(1, 2, size=(1000, 2000))  
print(norm)
norm.mean(axis = 0)

[[ 0.2567261   0.2145499   1.10187585 ... -0.8114663  -3.58530788
   3.21367622]
 [ 4.1662421   0.69411747  3.18684085 ...  1.40803225  1.29756314
   4.7958164 ]
 [ 2.43414533 -2.57690952  1.56202907 ...  1.28850037  5.51255557
  -0.18552503]
 ...
 [ 4.80679686  4.26161583  0.48772412 ...  1.61665197  3.27592167
  -1.22131779]
 [ 3.80960026 -0.01326456  1.96983264 ...  0.87362663 -0.55881422
   3.10777425]
 [ 1.48739383  2.49342043 -0.5585912  ...  4.00167813  1.86013086
   2.40823385]]


array([1.02558895, 1.00632397, 1.05287546, ..., 1.00715175, 1.00981987,
       0.92022126], shape=(2000,))

In [48]:
norm.var(axis = 0)

array([3.87249513, 3.84525372, 4.52235772, ..., 4.23996667, 3.81814362,
       3.72603541], shape=(2000,))

In [54]:
import numpy as np
N = int(input("количество точек: "))

n_arr = np.random.normal(size=(N, 2))
print(n_arr)
print(" ---- ")
mean_arr = n_arr.mean(axis=0)
print(mean_arr)
av_x = mean_arr[0]
print(" ---- ")
print(av_x)

av_y = mean_arr[1]
print(av_y)

print(" ---- ")

std_arr = n_arr.std(axis=0)

std_x = std_arr[0]
print(std_x)

std_y = std_arr[1]

количество точек:  10


[[-0.70063572  1.26783113]
 [-0.93453354  2.05300655]
 [ 0.9324513  -0.20260742]
 [-0.3888605   0.16646431]
 [-0.38924809 -0.85205203]
 [ 1.88846838  0.64372182]
 [-0.06641171 -0.44146192]
 [ 0.85817539 -0.05162305]
 [-0.43732582  0.07157016]
 [ 0.47436886 -0.18593512]]
 ---- 
[0.12364485 0.24689144]
 ---- 
0.12364485394307803
0.2468914422775832
 ---- 
0.8430316037429709
